#!/bin/bash

# Написать скрипт разбора логов, скрипт запрашивает имя процесса и ищет для него логи, вводит их на экран за указанный промежуток времени.
# Большинство логов хранятся в папке /var/log. Скрипт по очереди проверяет наличие файла с именем процесса в папке /var/log/, если файл найден — проверяет его на наличие в нем требуемой информации, если его нет, проверяет наличие папки с имененем процесса, при нахождении папки скрипт просматривает все файлы в этой папке на предмет нахождения в ней требуемой информации, если не найдена папка, то информация ищется в syslog.
# Если информация найдена, выводятся записи за указанный пользователем промежуток времени (пользователю выводится формат и границы временного интервала, за который существует лог).

echo -n "Enter the process name: "
read PROC

#file exists and not empty

if [ -f /var/log/$PROC.log ]
then
	FILE=/var/log/$PROC.log
	
fi
if [ -d /var/log/$PROC ]
then
	FILE=/var/log/$PROC
fi

#try to find in syslog
if [ `cat /var/log/syslog | grep $PROC | wc -l ` -gt 0 ]
then
	FILE=/var/log/syslog
fi

DATE1=`cat $FILE | sed -n 1p | cut -d ' ' -f1,2,3`
echo "Log from $DATE1 is available." 
echo -n "Enter the period starting (MON DD HH:MM:SS): "
read PERIOD_START
echo -n "Enter the period ending (MON DD HH:MM:SS): "
read PERIOD_END

while read LINE
	do
		STR_DATE=`echo $LINE | cut -d ' ' -f1,2,3`
		if (( `date --date="$STR_DATE" +%s` > `date --date="$PERIOD_START" +%s` &&  `date --date="$STR_DATE" +%s` < `date --date="$PERIOD_END" +%s` ));
		then
			echo $LINE
		fi
done < $FILE

